#spring:
#  profiles:
#    active: dev
#
#---
#
#spring:
#  profiles: dev
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://admingoodbam.c2upt41eupiw.ap-northeast-2.rds.amazonaws.com:3306/goodbam
#    username: admingoodbam
#    password: projectgoodbam
#  mvc:
#    view:
#      prefix: /WEB-INF/jsp/
#      suffix: .jsp
#    static-path-pattern: /resources/**
#
#server:
#  port: 8070
#
#---



